services:
  # -------------------------------
  # Search Head 1
  # -------------------------------
  sh1:
    image: splunk/splunk:9.0.3-openjdk11
    container_name: sh1
    hostname: sh1
    networks:
      - skynet
    ports:
      - "8005:8000"
      - "8095:8089"
    environment:
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
    volumes:
    - sh1_etc:/opt/splunk/etc
    - sh1_var:/opt/splunk/var
    tty: true
    stdin_open: true
    restart: unless-stopped
  # -------------------------------
  # Search Head 2
  # -------------------------------
  sh2:
    image: splunk/splunk:9.0.3-openjdk11
    container_name: sh2
    hostname: sh2
    networks:
      - skynet
    ports:
      - "8006:8000"
      - "8096:8089"
    environment:
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
    volumes:
    - sh2_etc:/opt/splunk/etc
    - sh2_var:/opt/splunk/var
    tty: true
    stdin_open: true
    restart: unless-stopped
  # -------------------------------
  # Search Head 3
  # -------------------------------
  sh3:
    image: splunk/splunk:9.0.3-openjdk11
    container_name: sh3
    hostname: sh3
    networks:
      - skynet
    ports:
      - "8007:8000"
      - "8097:8089"
    environment:
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
    volumes:
    - sh3_etc:/opt/splunk/etc
    - sh3_var:/opt/splunk/var
    tty: true
    stdin_open: true
    restart: unless-stopped
  # -------------------------------
  # Deployer
  # -------------------------------
  dep1:
    image: splunk/splunk:9.0.3-openjdk11
    container_name: dep1
    hostname: dep1
    networks:
      - skynet
    ports:
      - "8008:8000"
      - "8098:8089"
    environment:
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
    volumes:
    - dep1_etc:/opt/splunk/etc
    - dep1_var:/opt/splunk/var
    tty: true
    stdin_open: true
    restart: unless-stopped
# -------------------------------
# Networks
# -------------------------------
networks:
  skynet:
    external: true
# -------------------------------
# Named Volumes
# -------------------------------
volumes:
  sh1_etc:
  sh1_var:
  sh2_etc:
  sh2_var:
  sh3_etc:
  sh3_var:
  dep1_etc:
  dep1_var:
