# ==================================================
# Splunk Search Head Cluster Environment
# --------------------------------------------------
# - 3 Search Heads (SH1 Captain)
# - 1 Deployer
# - SHC Secret shared across all nodes
# - Requires .env file
# ==================================================

version: '3.8'

services:
  sh1:
    image: splunk/splunk:9.0.3-openjdk11
    container_name: sh1
    hostname: sh1
    networks:
      - skynet
    ports:
      - "8005:8000"
      - "8094:8089"
    environment:
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_SEARCH_HEAD_URL: sh1,sh2,sh3
      SPLUNK_SEARCH_HEAD_CAPTAIN_URL: sh1
      SPLUNK_ROLE: splunk_search_head
      SPLUNK_DEPLOYER_URL: dep1
      SPLUNK_SHC_SECRET: ${SPLUNK_SHC_SECRET}
    tty: true
    stdin_open: true
    restart: unless-stopped

  sh2:
    image: splunk/splunk:9.0.3-openjdk11
    container_name: sh2
    hostname: sh2
    networks:
      - skynet
    ports:
      - "8006:8000"
      - "8095:8089"
    environment:
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_SEARCH_HEAD_URL: sh1,sh2,sh3
      SPLUNK_SEARCH_HEAD_CAPTAIN_URL: sh1
      SPLUNK_ROLE: splunk_search_head
      SPLUNK_DEPLOYER_URL: dep1
      SPLUNK_SHC_SECRET: ${SPLUNK_SHC_SECRET}
    tty: true
    stdin_open: true
    restart: unless-stopped

  sh3:
    image: splunk/splunk:9.0.3-openjdk11
    container_name: sh3
    hostname: sh3
    networks:
      - skynet
    ports:
      - "8007:8000"
      - "8096:8089"
    environment:
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_SEARCH_HEAD_URL: sh1,sh2,sh3
      SPLUNK_SEARCH_HEAD_CAPTAIN_URL: sh1
      SPLUNK_ROLE: splunk_search_head
      SPLUNK_DEPLOYER_URL: dep1
      SPLUNK_SHC_SECRET: ${SPLUNK_SHC_SECRET}
    tty: true
    stdin_open: true
    restart: unless-stopped

  dep1:
    image: splunk/splunk:9.0.3-openjdk11
    container_name: dep1
    hostname: dep1
    networks:
      - skynet
    ports:
      - "8008:8000"
      - "8097:8089"
    environment:
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_ROLE: splunk_deployer
      SPLUNK_SHC_SECRET: ${SPLUNK_SHC_SECRET}
    tty: true
    stdin_open: true
    restart: unless-stopped

networks:
  skynet:
    external: true
